/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioninscription;
import java.awt.Color;
import java.awt.Label;
import java.sql.*;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import sql.*;
/**
 *
 * @author Administrateur
 */
public class FenInscription extends javax.swing.JFrame {

    /**
     * Creates new form FenInscription
     */
    Connection conn;
    Statement stmt1, stmt2;
    
    public FenInscription()
    {
        initComponents();
        btnInscription.setVisible(false); // On rend le bouton inscription non visible
        tableFormations.selectAll();
        tableFormations.setDefaultRenderer(Object.class, new Couleur()); // Pour mettre les sessions déficitaires en rouge
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        lblMatricule = new javax.swing.JLabel();
        cbxMatricule = new javax.swing.JComboBox();
        scrollPaneFormations = new javax.swing.JScrollPane();
        tableFormations = new javax.swing.JTable();
        btnInscription = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscription des clients aux différentes sessions");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitre.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("GESTION DES INSCRIPTIONS");
        lblTitre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblMatricule.setText("Matricule : ");

        cbxMatricule.setName("cmbMat"); // NOI18N
        cbxMatricule.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMatriculeItemStateChanged(evt);
            }
        });
        cbxMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMatriculeActionPerformed(evt);
            }
        });

        tableFormations.setModel(new ModeleJTableListeSession());
        tableFormations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFormationsMouseClicked(evt);
            }
        });
        tableFormations.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tableFormationsInputMethodTextChanged(evt);
            }
        });
        scrollPaneFormations.setViewportView(tableFormations);

        btnInscription.setText("Inscription");
        btnInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                    .addComponent(scrollPaneFormations)
                    .addComponent(btnInscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(scrollPaneFormations, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            try
            {
                // On prévoit 2 connexions à la base
                stmt1 = GestionBdd.connexionBdd(GestionBdd.TYPE_MYSQL, "formarmor","localhost", "root","");
                stmt2 = GestionBdd.connexionBdd(GestionBdd.TYPE_MYSQL, "formarmor","localhost", "root","");
                // Liste des clients qui "ont un plan de formation"
                String req = "select distinct c.matricule from client c, plan_formation p "
                 + "where c.matricule = p.matricule order by c.matricule";
                ResultSet rs = GestionBdd.envoiRequeteLMD(stmt1,req);
                cbxMatricule.addItem("---");
                while (rs.next())
                {
                    cbxMatricule.addItem(rs.getString(1));
                }
            }
            catch (SQLException se)
            {
                System.out.println("Erreur SQL1 : " + se.getMessage());
            }
    }//GEN-LAST:event_formWindowOpened

    private void cbxMatriculeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMatriculeItemStateChanged
        // Affichage du nom prénom et de la liste des sessions autorisées
        if (evt.getStateChange() != 1) // Pour éviter le déclenchement sur la création de la fenêtre
        {
            renseigne();
        }
        btnInscription.setVisible(false);
    }//GEN-LAST:event_cbxMatriculeItemStateChanged

    private void btnInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscriptionActionPerformed
        FenConfirmationInscription f2 = new FenConfirmationInscription(this, true);
        f2.init(cbxMatricule.getSelectedItem(), tableFormations.getValueAt(tableFormations.getSelectedRow(),0));
        f2.setSize(400,300);
        f2.setVisible(true);
    }//GEN-LAST:event_btnInscriptionActionPerformed

    private void tableFormationsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tableFormationsInputMethodTextChanged
        //
    }//GEN-LAST:event_tableFormationsInputMethodTextChanged

    private void tableFormationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFormationsMouseClicked
        if (cbxMatricule.getSelectedIndex()>0 && tableFormations.getValueAt(tableFormations.getSelectedRow(), 0) != null)
        {
            btnInscription.setText("Inscription");
            btnInscription.setVisible(true);
        }
        else
        {
            btnInscription.setVisible(false);
        }
    }//GEN-LAST:event_tableFormationsMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        renseigne();
    }//GEN-LAST:event_formWindowActivated

    private void cbxMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMatriculeActionPerformed
    private void renseigne()
    {
        try
        {
        // On vide le JTable
            int j, k;
            String req;
            for(int i=0;i<tableFormations.getRowCount();i++)
            {
                for (j=0;j<tableFormations.getColumnCount();j++)
		{
                    tableFormations.setValueAt(null,i,j);
		}
            }
            if (cbxMatricule.getSelectedIndex()==0 || cbxMatricule.getSelectedItem()== null) // Pas de client de choisi
            {
                // Toutes les sessions
                req = "select null, s.numero, s.libelleform, s.niveauform, s.datedebut, duree, nb_places, nb_inscrits, coutrevient ";
                req += "from session_form s, formation f ";
                req += "where s.libelleform = f.libelle and s.niveauform = f.niveau ";
                // et date supérieure à la date du jour
                btnInscription.setVisible(false); // On rend le bouton inscription non visible
            }
            else
            {
                // Sélection des sessions "autorisées"
                req = "select c.nom, s.numero, s.libelleform, s.niveauform, s.datedebut, duree, nb_places, nb_inscrits, coutrevient ";
                req += "from session_form s, client c, plan_formation p, formation f ";
                req += "where c.matricule = '" + cbxMatricule.getSelectedItem() + "' ";
                req += "and p.matricule = c.matricule and nb_places > nb_inscrits ";
                req += "and p.libelle_form = f.libelle and p.niveau = f.niveau ";
                req += "and s.libelleform = f.libelle and s.niveauform = f.niveau ";
                // et date supérieure à la date du jour
                req += "and close = 0 and effectue = 0 and s.numero Not In ";
                req += "(Select num_session From inscription Where matricule = '" + cbxMatricule.getSelectedItem() + "')";
                if (tableFormations.getValueAt(tableFormations.getSelectedRow(), 0) != null) //Si la cellule sélectionnée est vide
                {
                    btnInscription.setVisible(false); // On rend le bouton inscription non visible
                }
            }
            stmt1 = GestionBdd.connexionBdd(GestionBdd.TYPE_MYSQL, "formarmor","localhost", "root","");
            ResultSet rs2 = GestionBdd.envoiRequeteLMD(stmt1, req);
            ResultSet rs3 = null;
            
            k = 0;
            try
            {
                while(rs2.next())
                {
                    // On calcule la marge et on renseigne la dernière colonne(7ème) du jTable
                    req = "Select sum(taux_horaire) as revenu_session ";
                    req += "from statut st, session_form s, client c, inscription i ";
                    req += "where s.numero = i.num_session and c.matricule = i.matricule ";
                    req += "and c.typestatut = st.type and s.numero = " + rs2.getInt(2);
                    stmt2 = GestionBdd.connexionBdd(GestionBdd.TYPE_MYSQL, "formarmor","localhost", "root","");
                    rs3 = GestionBdd.envoiRequeteLMD(stmt2, req);
                    rs3.first();
                    tableFormations.setValueAt((rs3.getFloat(1) - rs2.getFloat(9)), k, 7);
                    // On renseigne le reste du jTable
                    for (j=0;j<(tableFormations.getColumnCount() -1);j++)
                    {
                        tableFormations.setValueAt(rs2.getObject(j+2), k, j);
                    }
                    k++;
                }
                rs2.close();
            }
            catch (SQLException sqle)
            {
                System.out.print("Erreur SQL : " + sqle.getMessage());
            }
        }
        catch(NullPointerException npe)
        {
            System.out.println("Erreur : " + npe.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscription;
    private javax.swing.JComboBox cbxMatricule;
    private javax.swing.JLabel lblMatricule;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JScrollPane scrollPaneFormations;
    private javax.swing.JTable tableFormations;
    // End of variables declaration//GEN-END:variables
}
